spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    # thymeleaf cache 비활성화
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/test
    username: testuser
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  api-docs:
    path : /api-docs
    enabled: true
